# syntax=docker/dockerfile:1
FROM ruby:3.3.0

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /chat-app

COPY Gemfile .
COPY Gemfile.lock .

RUN bundle install

COPY . .

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
